### ISSUE TITLE
Replace or Update the file

### ISSUE THREAD

**Issue by kunalkamble** [NebulousLabs/nodejs-skynet#2]
I can see only upload or download the file, How can I Update/Replace or Delete the file at that location?

**Comment by kwypchlo** [comment]
Hello @kunalkamble, sorry for taking this long to write back. Skynet network currently does not support updating, replacing or deleting once uploaded content. If you wish to update your uploaded data, you will need to upload it again and it will become available within a new skylink. You have to keep in mind though that previously uploaded data will still be available within the original skylink until the hosting contract expires.

**Comment by DavidVorick** [comment]
If you are running the node yourself, you can delete the file using the `siac renter delete` or the `siac skynet unpin` commands. From the API, this uses the '/renter/delete' endpoint, which is not exposed on Skynet portals
